### PR TITLE
Front page reports

### PR DESCRIPTION
**Pull request by vanoudt**
Allow reports to be set to show on the main home page. Any reports can have the box ticked to show their results on the main page.
There is also another checkbox to allow overriding the necessity to have the "RunReports" permission. My thinking on this is that some reports should be allowed regardless of this... Perhaps a new permission should rather be added - something like "Allow running reports as widgets"... but I'm not sure how the permissions system works. What do you think @tbar0970 ?

### CODE REVIEW

**Comment by vanoudt** [comment]
Hi Tom! Any thoughts on this. Using this in production, and it's really useful. This way, we can see, for instance, upcoming important dates without having to manually go run a report...

**Comment by tbar0970** [comment]
Sorry for the delay!  Just moved house and I'm not sure I'll have time to review and merge it for a few weeks.  But the idea is a good one so I'll merge it eventually!

**Comment by vanoudt** [comment]
Not a problem 😀

**Comment by tbar0970** [comment]
Just had time for a quick look at this.  A few suggestions:
1. What's the reason for having an additional table frontpage_person_query instead of just adding two columns to the person_query table?  Seems to add a lot of complexity that could be avoided.
2. On the homepage the title is "Person Report #123 results" - wouldn't it make more sense to use the saved name of the query?
3. For code cleanliness can we please not have SQL in view_home.class.php.  SQL belongs in db_object classes.  If you followed suggestion #1 above you could just do something like
```
 $GLOBALS['system']->getDBObjectData('person_query', Array('show_on_homepage' => 1))
```

**Comment by vanoudt** [comment]
Have just modified this according to your suggestions.
1. I was using an additional table because it seemed more sensible to separate out details that weren't needed in that table. But instead, I've now used a single column added to the person_query table.

2. That should only have arrived if there wasn't a name associated with the query. This shouldn't occur anymore with the new design

3. Done!

**Comment by tbar0970** [comment]
Merged manually - see 61f04af51a39d70864a38d863daf59291503e1ce

To avoid magic numbers in the database, I changed the new column to a varchar which contains either blank string, 'auth' or 'all'.  You'll need to update this column definition on your system that already has these changes.

I also pulled out the whitespace changes into a separate commit - hopefully this is the end of them!

**Pull request closed without merging**
