### PR TITLE
Roster Reminder Script

### PR DESCRIPTION
**Pull request by s4069b**
This pull request includes roster_reminder.php and roster_reminder_sample.ini

This is my second go at a roster reminder script (I closed my last pull request) - and is much closer to ready. 

The ini file can be used to choose between including a table or a list of roster assignments (the list being easier to read on a phone).

When DEBUG is set to 1 in the ini file - the script will only send emails to the nominated 'roster coordinator'. So don't forget to make DEBUG 0  in the ini file before going 'live'.

### CODE REVIEW

**Comment by tbar0970** [comment]
Looks good!  Thanks for contributing.  I will review it properly in the next few weeks.

**Comment by vanoudt** [comment]
I've made some changes to this *FANTASTIC* pull request! This is something I've been doing manually, and am very keen on this. As well as emailing out roster reminders, we also send out SMS messages. Not sure how to add to this pull request, so have started my own. Includes all the changes here, plus the SMS changes. s4069b - I'd be more than happy if you accept my pull request into your tree, updating this pull reqeust.

Otherwise there's all your work also in pull request #445

**Comment by s4069b** [comment]
thanks for this.  Actually I have not looked at the code I put on GitHub for some time and may have made further changes to what I've been using locally. But I'm more than happy to run with yours and let things adjust from there (I have not tried yours yet). 

With our install I have three cron jobs during the week... the earliest being for the music and service leading rosters and then a kids ministry roster.. then the other tasks/rosters later in the week.  

The script sends me an error in school holidays when the kids roster is empty... I've been meaning to add a condition that if there's no email addresses (or now no SMS too I guess) then notify the roster coordinator/s that they may have some gaps to fill.

**Comment by s4069b** [comment]
It would be nice to have a big umbrella cron job set-up once which runs a script that interacts with the jethro database in such a way that allows us to add roster reminders and email reports via the jethro-pmm gui.

**Comment by vanoudt** [comment]
Agreed - that would be very nice. In fact, I'd want to go further and get rid of INI files completely - and have a totally GUI based system...

I've spent a bit of time tidying this up, and have changed the notification system a bit. The co-ordinator gets notified for every roster ... this might fulfill your requirement above?

Done some testing - and it all seems good on this end! Just set it to go live this Friday!

**Comment by vanoudt** [comment]
PS: Have added a condition in for when there are no assignees for a particular roster!

**Comment by s4069b** [comment]
Sounds good. 

My local copy is out of sync with GitHub. I had a quick look at what I had posted here and at your new pull request. And I think what I am currently using has an advantage with the emails. 

My current local version allows me to choose between including the roster as a table or as a list. I have been using the list only for the last few months because it is much easier to read on phone screens and the like. 

I have simply pasted my current .php file below as I don't have time currently. Feel free to take a look if you like. Otherwise I'll get back to it when i am able. But If I come back at it I'll come in on your newer version. 




application/x-httpd-php roster_reminder.php ( PHP script, ASCII text, with very long lines )

<?php
/*****************************************************************
This script will send roster reminder emails
set-up a cron-job to run the script ast follows

php /path/to/this/script/roster_reminder.php /path/to/ini/file/roster_reminder_sample.ini

Note: This script will only work with roster views that are made public
Where's the roster id number?  When you view a roster via the /jethro/public directory you'll see the roster id number in the url (eg. &roster_view=1)

Use .ini file to set the following
 - roster coordinator email / group
 - roster view number
 - pre_message to go with roster reminder
 - post_message to go with roster reminder
 - email from address
 - email from name
 - email subject
 - debug (only send to roster coordinator)
 - email method (email_class or php mail())

TWO EMAILS WILL BE SENT
 - one email to the assignees (to: roster coordinator bcc: assignees - content = roster table, roster message, how to tell the roster coordinator if you can't do the task allocated to you etc.
 - second email to the roster coordinator including a note listing those assignees w/o an email (i.e. who will not have received the email update)

IMPROVEMENTS?
When setting up a roster view there could be an option to include roster reminders. If including roster reminders then also the person (person id) or group (group id) who is/are the roster coordinator/s. And the time when you want the roster reminder to be sent (remembering that the server Jethro sits on may be operating in a different time-zone).
******************************************************************/
//
//pull varialbes in from ini file
//
if (empty($_SERVER['argv'][1]) || !is_readable($_SERVER['argv'][1])) {
	echo "You must specify an ini file as the first argument \n";
	echo "Eg:  php email_report.php email_report_sample.ini \n";
	exit;
}
ini_set('display_errors', 1);
$ini = parse_ini_file($_SERVER['argv'][1]);
//this is a bit verbose - to aid with fault-finding/testing
$roster_coordinator=$ini['ROSTER_COORDINATOR'];
$roster_id=$ini['ROSTER_ID'];
$pre_message=$ini['PRE_MESSAGE'];
$post_message=$ini['POST_MESSAGE'];
$email_from=$ini['EMAIL_FROM'];
$email_from_name=$ini['EMAIL_FROM_NAME'];
$email_subject=$ini['EMAIL_SUBJECT'];
$list_not_table=$ini['LIST_NOT_TABLE'];
//
$debug=$ini['DEBUG'];
$verbose=$ini['VERBOSE'];
$phpMail=$ini['PHP_MAIL'];
//
//setup the includes etc
//
define('JETHRO_ROOT', dirname(dirname(__FILE__)));
set_include_path(get_include_path().PATH_SEPARATOR.JETHRO_ROOT);
if (!is_readable(JETHRO_ROOT.'/conf.php')) {
	trigger_error('Jethro configuration file not found.  You need to copy conf.php.sample to conf.php and edit it before Jethro can run', E_USER_ERROR);
	exit(1);
}
require_once JETHRO_ROOT.'/conf.php';
define('DB_MODE', 'private');
//if (!defined('DSN')) define('DSN', constant('PRIVATE_DSN'));
require_once JETHRO_ROOT.'/include/init.php';
require_once JETHRO_ROOT.'/include/user_system.class.php';
$GLOBALS['user_system'] = new User_System();
$GLOBALS['user_system']->setPublic();
require_once JETHRO_ROOT.'/include/system_controller.class.php';
$GLOBALS['system'] = System_Controller::get();
require_once JETHRO_ROOT.'/db_objects/roster_view.class.php';
//
//get the roster information using the roster view id
//
$view = $GLOBALS['system']->getDBObject('roster_view', $roster_id);
				$start_date = date("Ymd");
				$end_date = date('Ymd', strtotime("+6 day"));
//
//build the roster table to be included in the email/s
//
//get the roster name
ob_start();
$view->printFieldValue('name');
$roster_name = ob_get_contents();
ob_end_clean();
//we will include this weeks roster either as a list or as a table
//start with a list
if ((int)$list_not_table==1) {
//get the roster as csv
ob_start();
$view->printCSV($start_date, $end_date);
$roster_csv = ob_get_contents();
ob_end_clean();
//break the csv into lines. trick is there are new lines in some fields so break when new-line and quotes /n" but we want to retain the " so use lookahead(?=  ). 
$roster_lines = preg_split('/(?=\n")/',$roster_csv);
$roster_array = array();
foreach ($roster_lines as $line) {
    $roster_array[] = str_getcsv($line);
}
//now turn the array into a list of roster assignments 
$roster=$roster_array[0][1].'<br>';
$fields=count($roster_array[1]);
$x=0;
While ($x < $fields) {
	$roster.= '<b>'.$roster_array[1][$x].'</b><br>';
	if ($roster_array[2][$x]=="") {
	$roster.= '<i>nil</i><br><br>';
	} else {
	$roster.= preg_replace("/\\n/m", "<br />",$roster_array[2][$x]).'<br><br>';
	}
  $x++;
  }
} else { 
// otherwise include as a table
ob_start();
$view->printView($start_date, $end_date, FALSE, TRUE);
$roster = ob_get_contents();
ob_end_clean();
}
//put the other details into the email
$longstring = "<html><head><style>html body { font-family: sans-serif;}</style></head><body>";
$longstring.=$pre_message."<br>";
$longstring.="<b>Roster: ";
$longstring.=$roster_name."</b>";
$longstring.='<br>'.$roster;
$longstring.="<br>".$post_message;
$longstring.="<br><br><i>This email was generated by the ".SYSTEM_NAME." Jethro system.</i><br>"; 
$longstring.="</body></html>";
//
//build the email address array / no email address array
//
$emails=array();
$no_emails=array();
$assignees=$view->getAssignees($start_date, $end_date);
foreach($assignees as $row => $innerArray){
    if (!empty($innerArray['email'])){
     	$emails[]=$innerArray['email'];
     } else {
	$no_emails[]=$innerArray['first_name']." ".$innerArray['last_name'];
     }
    }
//strip any duplicates
$emails = array_unique($emails);
$emails_string = (implode(',',$emails));
// if DEBUG then only send an email to the specified roster coordinator
if ((int)$debug==1){
 $emails_string=$roster_coordinator;
}
$no_emails = array_unique($no_emails);
$no_emails_string = (implode('<br>', $no_emails));
//
//send the emails
//
$no_email_address_message="Jethro has just sent a roster reminder email regarding this roster - <b>".$roster_name." </b><br><br> But the following people do not have an email address recorded and so they have not been sent the reminder:<br>".$no_emails_string;
$email_not_sent_subject="warning re: ".$email_subject;
//if DEBUG then echo the email content
if ((int)$debug==1){
echo $longstring."<br>";
}
//
//send using built in email class
//
if ((int)$phpMail==0) {
require_once JETHRO_ROOT.'/include/emailer.class.php'; 
	$message = Emailer::newMessage()
	  ->setSubject($email_subject)
	  ->setFrom(array($email_from => $email_from_name))
	  ->setBody("roster reminder email")
	  ->addPart($longstring, 'text/html')
	  ->setTo(explode(',',$roster_coordinator))
	  ->setBcc(explode(',',$emails_string));
	$res = Emailer::send($message);
	if (!$res) {
		echo "Failed to send roster reminder (".$roster_name.")\n";
		exit(1);
	} else {
		if (!empty($verbose)) {
			echo "Sent roster reminder (".$roster_name.")\n";
		}
	}
// send an email to the roster coordinator if anyone does not have an email address   
if (!empty($no_emails)){
	$message2 = Emailer::newMessage()
	  ->setSubject($email_not_sent_subject)
	  ->setFrom(array($email_from => $email_from_name))
	  ->setBody("warning re roster reminder email")
	  ->addPart($no_email_address_message, 'text/html')
	  ->setTo(explode(',',$roster_coordinator));
	$res = Emailer::send($message2);
	if (!$res) {
		echo "Failed to send roster reminder warning to coordinator (".$roster_name.")\n";
		exit(1);
	} else {
		if (!empty($verbose)) {
			echo "Sent roster reminder warning to coordinator (".$roster_name.")\n";
		}
	}
	}
}
//using php mail()
if ((int)$phpMail==1) {
  $eol = PHP_EOL;
  $uid = md5(uniqid(time()));
  $email_to=$roster_coordinator;
  $header = "From: ".$email_from.$eol;
  $header .= "MIME-Version: 1.0".$eol;
  $header .= "Bcc: ".$emails_string.$eol;
  $header .= "Content-Type: multipart/mixed; boundary=\"".$uid."\"";
  $message = "--".$uid.$eol;
  $message .= "Content-type:text/html; charset=iso-8859-1".$eol;
  $message .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
  $message .= $longstring.$eol;
  $message .= "--".$uid."--";
   if (mail($email_to, $email_subject, "$message", $header)) {
   echo "Mail send roster reminder - ".$roster_name." sent OK <br>";
   } else {
   echo "Mail send roster reminder - ".$roster_name." send ERROR!";
   }
// send an email to the roster coordinator if anyone does not have an email address   
if (!empty($no_emails)){
	$email_to=$roster_coordinator;
   	$header = "From: ".$email_from.$eol;
  	$header .= "MIME-Version: 1.0".$eol;
  	$header .= "Content-Type: multipart/mixed; boundary=\"".$uid."\"";
  	$message = "--".$uid.$eol;
  	$message .= "Content-type:text/html; charset=iso-8859-1".$eol;
  	$message .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
  	$message .= $no_email_address_message.$eol;
  	$message .= "--".$uid."--";
    if (mail($email_to,$email_not_sent_subject,"$message",$header)){
    echo "email sent to coordinator";
    } else {
    echo "email failed to send to coordinator";
    }
  }
  }
?>

**Comment by vanoudt** [comment]
Thanks! Actually, that's also possible with the version you put on github here. I've just re-structured the code a bit, which might hide that fact. I have tested both list and table emails on my branch. (The table mode is nice - but can be a real pain when the tables are very wide. I've also defaulted to the "list" mode!)

If you're happy to go ahead with PR #445, Can I suggest closing this one so that Tom can focus on just the one?

**Comment by s4069b** [comment]
Sorry... I have not been giving this much attention. Just responding when emails have come through. 
I will close as you have suggested.

**Comment by tbar0970** [comment]
Just re

> It would be nice to have a big umbrella cron job set-up once which runs a script that interacts with the jethro database in such a way that allows us to add roster reminders and email reports via the jethro-pmm gui.

Yes it would.  But we'd need to do a fair bit of work to build GUIs for all the various scripts (mailchimp sync, date reminder, email report, roster reminder) - all of which might have several instantiations (eg two different reports sent out at different frequencies).  A good first step (in another issue) might be to mock up some interfaces and we could go from there.  But in the meantime INI files, whilst not beautiful, are quick and cheap!

**Comment by vanoudt** [comment]
Agreed

**Pull request closed without merging**
