### PR TITLE
Internationalization feature added

### PR DESCRIPTION
**Pull request by AndresSereno**
Here the pull request.

### CODE REVIEW

**Comment by hosios** [comment]
Great news. Thank you. 
Can I use it right away? or do I have to wait until it is merged, or until a new version comes out?

**Comment by tbar0970** [comment]
Theoretically you could merge this into your own Jethro repo on github.  But the best idea is to wait til I've merged it into a new Jethro release.  ETA is about 3 weeks.

**Comment by hosios** [comment]
@AndresSereno are you using the system in spanish? Is it good to use in production mode? Are the conflicts severe?

**Comment by tbar0970** [comment]
This has nearly reached the top of my to-do list.  Should be released within a couple of weeks.  Stay tuned!

**Comment by AndresSereno** [comment]
Hi, @hosios, 
Yes, I'm using the system in spanish, it's more a pre-prod environment since we are using it in our private network, migrating data from several excel files :).
The internationalization of administrative views is still pending. 
I don't see big conflicts with the trunk code, you could download  internationalization branch, start to work on it, and then merge easily with the head version, once is ready in a couple of weeks

**Comment by hosios** [comment]
Ok, I'll try that.
I don't need administrative vies in spanish right now, because it's just me using that part. Thank you for the response.

**Comment by tbar0970** [comment]
OK, I've just merged this to the master branch.
I can see a few places where there's some more work to do, but it's a great start.
I look forward to some more PRs as you find bits that need polishing :)

One thought for the future:  There are some places where Jethro displays a sentence like this:

> show attendance between [   ] and [   ] for congregation [   ]

Instead of translating three strings separately, with no context for the translator, it would be good to end up with something like this:
```sprintf(_("Show attendance between %s and %s for congregation %s"), $startChooseHTML, $endChooserHTML, $congChooserHTML)```
 - but I realise this would take a bit of work in some places.

Thanks again for your work on this.

**Comment by hosios** [comment]
Hello,

Sorry my ignorance. I installed the new system on top of my old version, but there where some issues with database tables missing (familyphoto). I fixed that one but then I decided to start fresh because I don't have that many records yet, and installed it in a new subfolder on my webserver. Went trough the installation process and all went well. But I can't find a way to use the spanish version of the site. What am I missing?

**Comment by tbar0970** [comment]
@AndresSereno can you give us some quick tips on how to set the locale?

**Comment by AndresSereno** [comment]
Yes, I'm going to share with you what I did y my local environment.

Right now I'm running Jethro in a Xamp installation over Windows
I will install the application in a Linux server next month, because we
are migrating to a new hosting provider.

So, in Xamp the application is in the /htdocs  folder.
Ex.  c:\xampp\htdocs\Jethro\

Edit config.php , adding the language setting
In our example

////////////////////////////////////////////////////////////
//LANGUAGE
////////////////////////////////////////////////////////////

define('LOCALE_DIR', 'c:\xampp\htdocs\Jethro\locale');
$locale = 'es_ES';
$domain = 'messages';
putenv('LC_ALL=' . $locale);
bindtextdomain($domain, LOCALE_DIR);
textdomain($domain);

We are setting here where the messages.mo is located
So our messages.mo files should be in
c:\xampp\htdocs\Jethro\locale\es\LC_MESSAGES\


It's all folks

Please let me know if you have some question or issue.

Cheers
Andres

**Comment by hosios** [comment]
I have my installation runing on a shared webhosting in Linux, and it is not working... I changed the LOCALE_DIR to a lot of different options, with no luck. I even hardcoded the complete url there, but nothing. Probably missing something.

Thank you anyways

**Comment by tbar0970** [comment]
@hosios on shared hosting you'll need to figure out the base directory of your account - it might be something like /home/users/hosios/  in which case your LOCALE_DIR would be something like /home/users/hosios/public_html/jethro/locale

If it's got cpanel I think there is something in cpanel (home page?) that tells you your account home dir.

**Pull request closed without merging**
