### PR TITLE
Issue 139 fixes

### PR DESCRIPTION
**Pull request by vanoudt**

### CODE REVIEW

**Comment by vanoudt** [comment]
This fixes issue 139 for me. SMSes can now be sent from reports.

**Comment by vanoudt** [comment]
To do: allow for "Send and move to next person" in the modal dialog

**Comment by vanoudt** [comment]
This now includes capacity to send SMS messages from reports. Also incorporates saving messages as notes (if so selected). Also incorporates a character count on messages. This is working very well for me at the moment.

**Comment by vanoudt** [comment]
Oops - accidentally closed pull request!

**Comment by vanoudt** [comment]
Please consider this for merging! :-)

**Comment by tbar0970** [comment]
Yep, this is on my todo list!  Just waiting til I have a bit of time to look through it.  Sounds good though.

**Comment by vanoudt** [comment]
:-) Thanks

**Comment by vanoudt** [comment]
I've submitted a new pull request, since this one doesn't apply properly anymore...

**Pull request closed without merging**
