### PR TITLE
Attendance auto headcount

### PR DESCRIPTION
**Pull request by vanoudt**
Hi Tom,

A quick pull request to scratch an itch of mine. This simply automatically increments or decrements the headcount for the current congregation/group when doing attendances. The value can still, of course, be changed manually. 
If the value is changing from Present->Unknown or Present->Absent, it decrements it by one.
If the value is changing from Unkown->Present or Absent->Present, it increments it by one.

When we have guests, I want to include them in the headcount. Up till now, I've been doing the attendance, hitting save to see the total members present, and then going back into attendance and adding in the number of visitors present. Doing it this way, I can mark everyone present or absent, and then manually add in the number of guests that I've counted...

### CODE REVIEW

**Comment by vanoudt** [comment]
This should mostly be mergeable - but I'm also using this branch as the place to tackle issue #200 since they're all headcount related!

**Comment by vanoudt** [comment]
Finally ready to merge, @tbar0970! (I hope!) This also addresses issue #200,for all styles of attendance recording and display!

There are some new tables required, of course...

**Comment by vanoudt** [comment]
Hi @tbar0970 

Just wondering if you can have a look at this. It's something that I've been using for some time now, and makes things _so_ much easier when doing attendances...

**Comment by tbar0970** [comment]
Thanks for the reminder, will look at it.

**Comment by vanoudt** [comment]
Thanks Tom!

**Comment by vanoudt** [comment]
Hi Tom,

Thanks for all you do - Jethro's going well! Just updated to the latest version, and found that I had to manually pull this in still. Any chance of taking a look at it at some time? No pressure - I know you must be busy!

**Comment by tbar0970** [comment]
I'm sorry for neglecting this PR for so long.
In https://github.com/tbar0970/jethro-pmm/issues/704 I've now added a display of the number-marked-present next to the headcount box, which I believe satisfies the same need.
So I'm going to close this PR. Let me know if there's some need that issue #704 doesn't meet.
image

**Pull request closed without merging**
