### PR TITLE
Doc merge updates

### PR DESCRIPTION
**Pull request by tim-pearce**
This pull request supersedes #791

Implements most of #743 plus a few issues with PHP 8.2 (#790) Still inefficient in how it handles attendance data.

- incorporates a recent version of TBS which works for PHP 5, 7 & 8 (I had to make changes for it to work with PHP 8.2)
- includes a 'Dump' facility which shows ALL fields available
- allows for storing templates on the server when used for rosters and attendance
- brings in 'extended' fields in reports
- provides separate tables for each member status (both congregation and group) where they exist
- help and examples are updated and extended
- rosters now includes a list of people on the roster

Tested on PHP 8.2 and 5.6

### CODE REVIEW

**Comment by tim-pearce** [comment]
Tom,
Any chance you could move this along? It's quite a bit of code for me to keep merging into Jethro whenever there is an update.

**Comment by tbar0970** [comment]
Hi Tim. I understand how applying your patches is a pain, and I'm sorry I've left these PRs unresolved for so long.  The challenge for me is that as project maintainer I need to review code before I 'take responsibility' for it in the main branch.

This PR has 23 changed files (8 of them are binary files - ODT examples etc). That's a lot of files to review.   It's also harder when there are several problems/enhancements being addressed in the one PR.  
For example I'm not clear how call_csv relates to document merge.

To give me a better chance of being able to understand and merge these, could I get you to submit some separate PRs for specific things.  For example your changes to general.php and the paginator class look like standalone issues - if you can submit a PR for each of those, with just one file changed,  and an explanation of the problem it's solving, I can merge those quickly.  And then I'll have a better chance of getting my head around a document-merge PR which has more extensive code but no other distractions.

Sorry to be a pain, but realistically this is the only pathway that I can see working, given the limited time I've got to review these.

**Comment by tim-pearce** [comment]
Tom, thanks for the feedback. I will break it down and add more explanations.
Some of those seemingly unrelated changes are because I am on PHP 8.2

**Comment by tim-pearce** [comment]
Superseded by latter requests

**Pull request closed without merging**
