### PR TITLE
Roster reminder script and ini file

### PR DESCRIPTION
**Pull request by s4069b**
Here is a first go at this .. improvements welcome.

### CODE REVIEW

**Comment by s4069b** [comment]
I have had another go at the email_report.php script and the way that it handles the html content of the email. this should avoid the previous issues with miss-handling spaces and newlines.

**Comment by s4069b** [comment]
ah... I actually broke the email_report.php script for reports that do not include the 'check-box' option. $html_string = strstr($html_string, 'With selected persons:', true) returns FALSE in that case. 
so change the line66 to this instead (i.e. so if 'with selected persons' is not found in the string it will instead return the string un-altered). Hope that makes sense. 

$html_string = strstr($html_string, 'With selected persons:', true)?: $html_string;

**Comment by tbar0970** [comment]
It's a good move to let the person_query object generate the HTML for you.  But I fear that stripping stuff out after the fact is not the best approach - too much to miss, to hard to strip exactly the right content.  

Perhaps you could pass a parameter to the printResults function to indicate you want "basic" HTML without checkboxes etc?

**Comment by s4069b** [comment]
I can have a look at that. thanks for the idea

**Comment by s4069b** [comment]
Somehow I've managed to get two script caught up in one pull request
- the roster_remider script
- changes to the email_report script

**Pull request closed without merging**
